fix github actions runner (#5192)
* fix github actions runner

sbt is no longer included by default in the ubuntu 24 runner
https://github.com/sbt/setup-sbt
https://github.com/actions/setup-java/issues/712#issuecomment-2557396980

* forgot a few places

* temporarily disable citation action

Error: Rscript: command not found
https://github.com/joernio/joern/pull/4069

* try to reenable citation action and configure to install R